#ifndef FUJINET_VERSION_H
#define FUJINET_VERSION_H

#define FNLIB_VERSION_MAJOR 5
#define FNLIB_VERSION_MINOR 0
#define FNLIB_VERSION_PATCH 5
#define FNLIB_VERSION_FULL "v5.0.5"

#endif /* FUJINET_VERSION_H */
